import React, { useState } from 'react';
import { ObligationItem } from '@/types/legal';
import { 
  Calendar, 
  Clock, 
  AlertCircle, 
  CheckCircle2, 
  Download, 
  Copy, 
  Check, 
  Filter,
  User,
  Building,
  Flag
} from 'lucide-react';

interface ObligationTimelineProps {
  obligations: ObligationItem[];
  documentTitle: string;
}

export default function ObligationTimeline({ obligations, documentTitle }: ObligationTimelineProps) {
  const [filterParty, setFilterParty] = useState<string>('ALL');
  const [copied, setCopied] = useState(false);

  const filteredObligations = obligations.filter(o => {
    if (filterParty === 'ALL') return true;
    if (filterParty === 'USER') return o.responsibleParty === 'USER' || o.responsibleParty === 'BOTH';
    if (filterParty === 'COUNTERPARTY') return o.responsibleParty === 'COUNTERPARTY' || o.responsibleParty === 'BOTH';
    return true;
  });

  const getPriorityBadge = (priority: ObligationItem['priority']) => {
    switch (priority) {
      case 'CRITICAL':
        return 'bg-red-500/15 text-red-700 dark:text-red-400 border-red-500/30';
      case 'IMPORTANT':
        return 'bg-amber-500/15 text-amber-700 dark:text-amber-400 border-amber-500/30';
      default:
        return 'bg-blue-500/15 text-blue-700 dark:text-blue-400 border-blue-500/30';
    }
  };

  const copyMarkdownChecklist = () => {
    const md = `# Obligation Checklist for ${documentTitle}
Generated by Lexi AI

${obligations.map((o, idx) => `### ${idx + 1}. ${o.description}
- **Deadline/Trigger**: ${o.deadlineOrTrigger}
- **Responsible**: ${o.responsibleParty}
- **Reference**: ${o.clauseReference}
- **Penalty for Breach**: ${o.penaltyForBreach}
- **Priority**: ${o.priority}
`).join('\n')}
`;
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadICS = () => {
    const icsContent = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Lexi AI//Legal Obligation Calendar//EN
${obligations.map((o, i) => `BEGIN:VEVENT
UID:lexi-ai-${i}-${Date.now()}@legal.ai
SUMMARY:${o.description} (${o.clauseReference})
DESCRIPTION:${o.penaltyForBreach} - Responsible: ${o.responsibleParty}
STATUS:CONFIRMED
END:VEVENT`).join('\n')}
END:VCALENDAR`;

    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `legal_obligations_${Date.now()}.ics`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 p-5 shadow-sm space-y-5">
      
      {/* Header & Export Tools */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-slate-100 dark:border-slate-800">
        <div>
          <div className="flex items-center gap-2">
            <Calendar className="w-5 h-5 text-blue-600" />
            <h2 className="text-lg sm:text-xl font-bold text-slate-900 dark:text-white">
              Obligation & Deadline Timeline
            </h2>
          </div>
          <p className="text-xs text-slate-500 mt-0.5">
            Chronological triggers, notice periods, payment milestones, and penalty cliffs
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={copyMarkdownChecklist}
            className="inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-2 rounded-lg bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 transition"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied Markdown' : 'Copy Checklist'}</span>
          </button>
          
          <button
            onClick={downloadICS}
            className="inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-2 rounded-lg bg-blue-600 hover:bg-blue-500 text-white transition shadow-sm"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export to Calendar (.ics)</span>
          </button>
        </div>
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center justify-between gap-3 bg-slate-50 dark:bg-slate-800/60 p-2.5 rounded-xl border border-slate-200 dark:border-slate-700/60 text-xs">
        <div className="flex items-center gap-2">
          <Filter className="w-3.5 h-3.5 text-slate-500" />
          <span className="font-semibold text-slate-700 dark:text-slate-300">Responsible Party:</span>
          <button
            onClick={() => setFilterParty('ALL')}
            className={`px-2.5 py-1 rounded-md font-medium transition ${
              filterParty === 'ALL'
                ? 'bg-white dark:bg-slate-700 text-blue-600 dark:text-blue-400 shadow-sm border border-slate-200 dark:border-slate-600'
                : 'text-slate-500 hover:text-slate-800'
            }`}
          >
            All ({obligations.length})
          </button>
          <button
            onClick={() => setFilterParty('USER')}
            className={`px-2.5 py-1 rounded-md font-medium transition ${
              filterParty === 'USER'
                ? 'bg-white dark:bg-slate-700 text-blue-600 dark:text-blue-400 shadow-sm border border-slate-200 dark:border-slate-600'
                : 'text-slate-500 hover:text-slate-800'
            }`}
          >
            Your Obligations
          </button>
          <button
            onClick={() => setFilterParty('COUNTERPARTY')}
            className={`px-2.5 py-1 rounded-md font-medium transition ${
              filterParty === 'COUNTERPARTY'
                ? 'bg-white dark:bg-slate-700 text-blue-600 dark:text-blue-400 shadow-sm border border-slate-200 dark:border-slate-600'
                : 'text-slate-500 hover:text-slate-800'
            }`}
          >
            Counterparty Duties
          </button>
        </div>
      </div>

      {/* Timeline Stream */}
      <div className="relative pl-6 space-y-6 before:absolute before:left-2.5 before:top-3 before:bottom-3 before:w-0.5 before:bg-slate-200 dark:before:bg-slate-800">
        {filteredObligations.map((item, idx) => (
          <div key={item.id} className="relative group">
            
            {/* Timeline Dot */}
            <div className={`absolute -left-6 top-1.5 w-5 h-5 rounded-full border-2 border-white dark:border-slate-900 flex items-center justify-center text-[10px] font-bold ${
              item.priority === 'CRITICAL'
                ? 'bg-red-500 text-white'
                : item.priority === 'IMPORTANT'
                ? 'bg-amber-500 text-white'
                : 'bg-blue-500 text-white'
            }`}>
              {idx + 1}
            </div>

            {/* Timeline Item Card */}
            <div className="bg-slate-50 dark:bg-slate-800/50 rounded-xl p-4 border border-slate-200 dark:border-slate-800 hover:border-blue-400 transition space-y-2">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <span className="flex items-center gap-1 text-xs font-bold text-slate-800 dark:text-slate-200 bg-white dark:bg-slate-700 px-2 py-0.5 rounded border border-slate-200 dark:border-slate-600">
                    <Clock className="w-3 h-3 text-blue-500" />
                    {item.deadlineOrTrigger}
                  </span>
                  <span className="text-xs text-slate-400">• {item.clauseReference}</span>
                </div>

                <div className="flex items-center gap-2">
                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded border ${getPriorityBadge(item.priority)}`}>
                    {item.priority}
                  </span>
                  <span className="text-[11px] font-medium text-slate-500 flex items-center gap-1">
                    {item.responsibleParty === 'USER' ? (
                      <>
                        <User className="w-3 h-3 text-indigo-500" />
                        <span>You (Signer)</span>
                      </>
                    ) : (
                      <>
                        <Building className="w-3 h-3 text-slate-500" />
                        <span>Counterparty</span>
                      </>
                    )}
                  </span>
                </div>
              </div>

              <h4 className="font-semibold text-sm text-slate-900 dark:text-white">
                {item.description}
              </h4>

              <div className="flex items-start gap-2 text-xs text-red-700 dark:text-red-300 bg-red-500/10 p-2.5 rounded-lg border border-red-500/20">
                <AlertCircle className="w-3.5 h-3.5 text-red-500 shrink-0 mt-0.5" />
                <div>
                  <strong className="font-semibold">Penalty for Non-Compliance:</strong>{' '}
                  {item.penaltyForBreach}
                </div>
              </div>
            </div>

          </div>
        ))}
      </div>

    </div>
  );
}
