/**
 * Use Case 6: Generate summaries, checklists, or actionable outputs
 * Extracts chronological obligations, trigger conditions, penalties,
 * and exports actionable Markdown checklists and iCalendar (.ics) schedule files.
 */
import { ContractHealthReport, ObligationItem } from '@/types/legal';
import { extractObligationsFromDocument } from '@/lib/legal-engine';

export function generateActionableOutputs(report: ContractHealthReport): {
  obligations: ObligationItem[];
  markdownChecklist: string;
  icsCalendarContent: string;
} {
  const obligations = extractObligationsFromDocument(report);

  const markdownChecklist = `# Actionable Legal Checklist: ${report.title}
Generated by Lexi AI

${obligations.map((o, idx) => `### ${idx + 1}. [${o.priority}] ${o.description}
- **Deadline/Trigger**: ${o.deadlineOrTrigger}
- **Responsible Party**: ${o.responsibleParty}
- **Clause Reference**: ${o.clauseReference}
- **Breach Penalty**: ${o.penaltyForBreach}
`).join('\n')}`;

  const icsCalendarContent = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Lexi AI//Legal Obligation Calendar//EN
${obligations.map((o, i) => `BEGIN:VEVENT
UID:lexi-ai-${i}-${Date.now()}@legal.ai
SUMMARY:${o.description} (${o.clauseReference})
DESCRIPTION:${o.penaltyForBreach} - Responsible: ${o.responsibleParty}
STATUS:CONFIRMED
END:VEVENT`).join('\n')}
END:VCALENDAR`;

  return {
    obligations,
    markdownChecklist,
    icsCalendarContent,
  };
}
